/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Usuario
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadHospede = new javax.swing.JMenu();
        menuCadHospedeCadastrar = new javax.swing.JMenuItem();
        menuCadHospedeConsultar = new javax.swing.JMenuItem();
        menuCadQuartos = new javax.swing.JMenu();
        menuCadQuartosCadastrar = new javax.swing.JMenuItem();
        menuCadQuartosConsultar = new javax.swing.JMenuItem();
        menuCadFuncionarios = new javax.swing.JMenu();
        menuCadFuncionariosCadastrar = new javax.swing.JMenuItem();
        menuCadFuncionariosConsultar = new javax.swing.JMenuItem();
        menuCadFornecedores = new javax.swing.JMenu();
        menuCadFornecedoresCadastrar = new javax.swing.JMenuItem();
        menuCadFornecedoresConsultar = new javax.swing.JMenuItem();
        menuCadProdutos = new javax.swing.JMenu();
        menuCadProdutosCadastrar = new javax.swing.JMenuItem();
        menuCadProdutosConsultar = new javax.swing.JMenuItem();
        menuCadServicos = new javax.swing.JMenu();
        menuCadServicosCadastro = new javax.swing.JMenuItem();
        menuCadServicosConsultar = new javax.swing.JMenuItem();
        menuReservas = new javax.swing.JMenu();
        menuReservasCadastrar = new javax.swing.JMenu();
        menuReservasConsultar = new javax.swing.JMenu();
        menuReservasFinalizar = new javax.swing.JMenu();
        menuVendas = new javax.swing.JMenu();
        menuVendasProdutos = new javax.swing.JMenu();
        menuVendasServicos = new javax.swing.JMenu();
        menuFinaceiro = new javax.swing.JMenu();
        menuFinaceiroContasAPagar = new javax.swing.JMenu();
        menuFinaceiroContasAPagarCadastrar = new javax.swing.JMenuItem();
        menuFinaceiroContasAPagarConsultar = new javax.swing.JMenuItem();
        menuFinaceiroContasAReceber = new javax.swing.JMenu();
        menuFinaceiroContasAReceberCadastrar = new javax.swing.JMenuItem();
        menuFinaceiroContasAReceberConsultar = new javax.swing.JMenuItem();
        menuFinaceiroBalanco = new javax.swing.JMenu();
        menuRelatorios = new javax.swing.JMenu();
        menuRelatoriosFinanceiro = new javax.swing.JMenu();
        menuRelatoriosFinanceiroContasAPagar = new javax.swing.JMenuItem();
        menuRelatoriosFinanceiroContasAReceber = new javax.swing.JMenuItem();
        menuRelatoriosFinanceiroBalanco = new javax.swing.JMenuItem();
        menuRelatoriosReservas = new javax.swing.JMenu();
        menuRelatoriosReservasQuartosDisponiveis = new javax.swing.JMenuItem();
        menuRelatoriosReservasQuartosOcupados = new javax.swing.JMenuItem();
        menuRelatoriosReservasFuturas = new javax.swing.JMenuItem();
        menuRelatoriosVendas = new javax.swing.JMenu();
        menuRelatoriosVendasProdutos = new javax.swing.JMenuItem();
        menuRelatoriosVendasServicos = new javax.swing.JMenuItem();
        menuRelatoriosHospedes = new javax.swing.JMenu();
        menuRelatoriosFuncionarios = new javax.swing.JMenu();
        menuRelatoriosFornecedores = new javax.swing.JMenu();
        menuSeguranca = new javax.swing.JMenu();
        menuSegurancaFazerBackup = new javax.swing.JMenu();
        menuSegurancaRestaurarBackup = new javax.swing.JMenu();
        menuFerramentas = new javax.swing.JMenu();
        menuFerramentasTelaDeFundo = new javax.swing.JMenu();
        menuFerramentasTelaDeFundoAddImagem = new javax.swing.JMenuItem();
        menuFerramentasTelaDeFundoRemoverImagem = new javax.swing.JMenuItem();
        menuFerramentasTelaDeFundoRestaurarPadrao = new javax.swing.JMenuItem();
        menuFerramentasSobreOSistema = new javax.swing.JMenu();
        menuBarSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastro.png"))); // NOI18N
        menuCadastro.setText("Cadastros   |");

        menuCadHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_hospede.png"))); // NOI18N
        menuCadHospede.setText("Hospedes");

        menuCadHospedeCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_salvar.png"))); // NOI18N
        menuCadHospedeCadastrar.setText("Cadastrar");
        menuCadHospede.add(menuCadHospedeCadastrar);

        menuCadHospedeConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_buscar.png"))); // NOI18N
        menuCadHospedeConsultar.setText("Consultar");
        menuCadHospedeConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospedeConsultarActionPerformed(evt);
            }
        });
        menuCadHospede.add(menuCadHospedeConsultar);

        menuCadastro.add(menuCadHospede);

        menuCadQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_quarto.png"))); // NOI18N
        menuCadQuartos.setText("Quartos");

        menuCadQuartosCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_quarto.png"))); // NOI18N
        menuCadQuartosCadastrar.setText("Cadastrar");
        menuCadQuartos.add(menuCadQuartosCadastrar);

        menuCadQuartosConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buscar.png"))); // NOI18N
        menuCadQuartosConsultar.setText("Consultar");
        menuCadQuartos.add(menuCadQuartosConsultar);

        menuCadastro.add(menuCadQuartos);

        menuCadFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_funcionario.png"))); // NOI18N
        menuCadFuncionarios.setText("Funcionários");

        menuCadFuncionariosCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_salvar.png"))); // NOI18N
        menuCadFuncionariosCadastrar.setText("Cadastrar");
        menuCadFuncionarios.add(menuCadFuncionariosCadastrar);

        menuCadFuncionariosConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_buscar.png"))); // NOI18N
        menuCadFuncionariosConsultar.setText("Consultar");
        menuCadFuncionarios.add(menuCadFuncionariosConsultar);

        menuCadastro.add(menuCadFuncionarios);

        menuCadFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_fornecedor.png"))); // NOI18N
        menuCadFornecedores.setText("Fornecedores");

        menuCadFornecedoresCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_salvar.png"))); // NOI18N
        menuCadFornecedoresCadastrar.setText("Cadastrar");
        menuCadFornecedores.add(menuCadFornecedoresCadastrar);

        menuCadFornecedoresConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_buscar.png"))); // NOI18N
        menuCadFornecedoresConsultar.setText("Consultar");
        menuCadFornecedores.add(menuCadFornecedoresConsultar);

        menuCadastro.add(menuCadFornecedores);

        menuCadProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_produtos.png"))); // NOI18N
        menuCadProdutos.setText("Produtos");

        menuCadProdutosCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_vender.png"))); // NOI18N
        menuCadProdutosCadastrar.setText("Cadastrar");
        menuCadProdutos.add(menuCadProdutosCadastrar);

        menuCadProdutosConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buscar.png"))); // NOI18N
        menuCadProdutosConsultar.setText("Consultar");
        menuCadProdutos.add(menuCadProdutosConsultar);

        menuCadastro.add(menuCadProdutos);

        menuCadServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_servicos.png"))); // NOI18N
        menuCadServicos.setText("Serviços");

        menuCadServicosCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_vender.png"))); // NOI18N
        menuCadServicosCadastro.setText("Cadastro");
        menuCadServicosCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadServicosCadastroActionPerformed(evt);
            }
        });
        menuCadServicos.add(menuCadServicosCadastro);

        menuCadServicosConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buscar.png"))); // NOI18N
        menuCadServicosConsultar.setText("Consultar");
        menuCadServicos.add(menuCadServicosConsultar);

        menuCadastro.add(menuCadServicos);

        jMenuBar1.add(menuCadastro);

        menuReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reservas.png"))); // NOI18N
        menuReservas.setText("Reservas   |");

        menuReservasCadastrar.setText("Cadastrar Reserva");
        menuReservas.add(menuReservasCadastrar);

        menuReservasConsultar.setText("Consultar Reserva");
        menuReservas.add(menuReservasConsultar);

        menuReservasFinalizar.setText("Finalizar Reserva");
        menuReservas.add(menuReservasFinalizar);

        jMenuBar1.add(menuReservas);

        menuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/consumo.png"))); // NOI18N
        menuVendas.setText("Vendas   |");

        menuVendasProdutos.setText("Produtos");
        menuVendas.add(menuVendasProdutos);

        menuVendasServicos.setText("Serviços");
        menuVendas.add(menuVendasServicos);

        jMenuBar1.add(menuVendas);

        menuFinaceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/financeiro.png"))); // NOI18N
        menuFinaceiro.setText("Financeiro   |");

        menuFinaceiroContasAPagar.setText("Contas a Pagar");

        menuFinaceiroContasAPagarCadastrar.setText("Cadastar");
        menuFinaceiroContasAPagar.add(menuFinaceiroContasAPagarCadastrar);

        menuFinaceiroContasAPagarConsultar.setText("Consultar");
        menuFinaceiroContasAPagar.add(menuFinaceiroContasAPagarConsultar);

        menuFinaceiro.add(menuFinaceiroContasAPagar);

        menuFinaceiroContasAReceber.setText("Contas a Receber");

        menuFinaceiroContasAReceberCadastrar.setText("Cadastrar");
        menuFinaceiroContasAReceber.add(menuFinaceiroContasAReceberCadastrar);

        menuFinaceiroContasAReceberConsultar.setText("Consultar");
        menuFinaceiroContasAReceber.add(menuFinaceiroContasAReceberConsultar);

        menuFinaceiro.add(menuFinaceiroContasAReceber);

        menuFinaceiroBalanco.setText("Balanço");
        menuFinaceiro.add(menuFinaceiroBalanco);

        jMenuBar1.add(menuFinaceiro);

        menuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorios.png"))); // NOI18N
        menuRelatorios.setText("Relatorios   |");

        menuRelatoriosFinanceiro.setText("Financeiro");

        menuRelatoriosFinanceiroContasAPagar.setText("Contas a Pagar");
        menuRelatoriosFinanceiroContasAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatoriosFinanceiroContasAPagarActionPerformed(evt);
            }
        });
        menuRelatoriosFinanceiro.add(menuRelatoriosFinanceiroContasAPagar);

        menuRelatoriosFinanceiroContasAReceber.setText("Contas a Receber");
        menuRelatoriosFinanceiro.add(menuRelatoriosFinanceiroContasAReceber);

        menuRelatoriosFinanceiroBalanco.setText("Balanço");
        menuRelatoriosFinanceiro.add(menuRelatoriosFinanceiroBalanco);

        menuRelatorios.add(menuRelatoriosFinanceiro);

        menuRelatoriosReservas.setText("Reservas");

        menuRelatoriosReservasQuartosDisponiveis.setText("Quartos Disponíveis");
        menuRelatoriosReservas.add(menuRelatoriosReservasQuartosDisponiveis);

        menuRelatoriosReservasQuartosOcupados.setText("Quartos Ocupados");
        menuRelatoriosReservas.add(menuRelatoriosReservasQuartosOcupados);

        menuRelatoriosReservasFuturas.setText("Reservas Futuras");
        menuRelatoriosReservas.add(menuRelatoriosReservasFuturas);

        menuRelatorios.add(menuRelatoriosReservas);

        menuRelatoriosVendas.setText("Vendas");

        menuRelatoriosVendasProdutos.setText("Produtos");
        menuRelatoriosVendas.add(menuRelatoriosVendasProdutos);

        menuRelatoriosVendasServicos.setText("Serviços");
        menuRelatoriosVendas.add(menuRelatoriosVendasServicos);

        menuRelatorios.add(menuRelatoriosVendas);

        menuRelatoriosHospedes.setText("Hospedes");
        menuRelatorios.add(menuRelatoriosHospedes);

        menuRelatoriosFuncionarios.setText("Funcionários");
        menuRelatorios.add(menuRelatoriosFuncionarios);

        menuRelatoriosFornecedores.setText("Fornecedores");
        menuRelatorios.add(menuRelatoriosFornecedores);

        jMenuBar1.add(menuRelatorios);

        menuSeguranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/seguranca.png"))); // NOI18N
        menuSeguranca.setText("Segurança   |");

        menuSegurancaFazerBackup.setText("Fazer Backup");
        menuSeguranca.add(menuSegurancaFazerBackup);

        menuSegurancaRestaurarBackup.setText("Restaurar Backup");
        menuSeguranca.add(menuSegurancaRestaurarBackup);

        jMenuBar1.add(menuSeguranca);

        menuFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ferramentas.png"))); // NOI18N
        menuFerramentas.setText("Ferramentas   |");

        menuFerramentasTelaDeFundo.setText("Tela de Fundo");

        menuFerramentasTelaDeFundoAddImagem.setText("Add Imagem");
        menuFerramentasTelaDeFundo.add(menuFerramentasTelaDeFundoAddImagem);

        menuFerramentasTelaDeFundoRemoverImagem.setText("Remover Imagem");
        menuFerramentasTelaDeFundo.add(menuFerramentasTelaDeFundoRemoverImagem);

        menuFerramentasTelaDeFundoRestaurarPadrao.setText("Restaurar Padrão");
        menuFerramentasTelaDeFundoRestaurarPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFerramentasTelaDeFundoRestaurarPadraoActionPerformed(evt);
            }
        });
        menuFerramentasTelaDeFundo.add(menuFerramentasTelaDeFundoRestaurarPadrao);

        menuFerramentas.add(menuFerramentasTelaDeFundo);

        menuFerramentasSobreOSistema.setText("Sobre o Sistema");
        menuFerramentas.add(menuFerramentasSobreOSistema);

        jMenuBar1.add(menuFerramentas);

        menuBarSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        menuBarSair.setText("Sair");
        jMenuBar1.add(menuBarSair);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadHospedeConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospedeConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospedeConsultarActionPerformed

    private void menuCadServicosCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadServicosCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadServicosCadastroActionPerformed

    private void menuRelatoriosFinanceiroContasAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatoriosFinanceiroContasAPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelatoriosFinanceiroContasAPagarActionPerformed

    private void menuFerramentasTelaDeFundoRestaurarPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFerramentasTelaDeFundoRestaurarPadraoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFerramentasTelaDeFundoRestaurarPadraoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuBarSair;
    private javax.swing.JMenu menuCadFornecedores;
    private javax.swing.JMenuItem menuCadFornecedoresCadastrar;
    private javax.swing.JMenuItem menuCadFornecedoresConsultar;
    private javax.swing.JMenu menuCadFuncionarios;
    private javax.swing.JMenuItem menuCadFuncionariosCadastrar;
    private javax.swing.JMenuItem menuCadFuncionariosConsultar;
    private javax.swing.JMenu menuCadHospede;
    private javax.swing.JMenuItem menuCadHospedeCadastrar;
    private javax.swing.JMenuItem menuCadHospedeConsultar;
    private javax.swing.JMenu menuCadProdutos;
    private javax.swing.JMenuItem menuCadProdutosCadastrar;
    private javax.swing.JMenuItem menuCadProdutosConsultar;
    private javax.swing.JMenu menuCadQuartos;
    private javax.swing.JMenuItem menuCadQuartosCadastrar;
    private javax.swing.JMenuItem menuCadQuartosConsultar;
    private javax.swing.JMenu menuCadServicos;
    private javax.swing.JMenuItem menuCadServicosCadastro;
    private javax.swing.JMenuItem menuCadServicosConsultar;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenu menuFerramentasSobreOSistema;
    private javax.swing.JMenu menuFerramentasTelaDeFundo;
    private javax.swing.JMenuItem menuFerramentasTelaDeFundoAddImagem;
    private javax.swing.JMenuItem menuFerramentasTelaDeFundoRemoverImagem;
    private javax.swing.JMenuItem menuFerramentasTelaDeFundoRestaurarPadrao;
    private javax.swing.JMenu menuFinaceiro;
    private javax.swing.JMenu menuFinaceiroBalanco;
    private javax.swing.JMenu menuFinaceiroContasAPagar;
    private javax.swing.JMenuItem menuFinaceiroContasAPagarCadastrar;
    private javax.swing.JMenuItem menuFinaceiroContasAPagarConsultar;
    private javax.swing.JMenu menuFinaceiroContasAReceber;
    private javax.swing.JMenuItem menuFinaceiroContasAReceberCadastrar;
    private javax.swing.JMenuItem menuFinaceiroContasAReceberConsultar;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuRelatoriosFinanceiro;
    private javax.swing.JMenuItem menuRelatoriosFinanceiroBalanco;
    private javax.swing.JMenuItem menuRelatoriosFinanceiroContasAPagar;
    private javax.swing.JMenuItem menuRelatoriosFinanceiroContasAReceber;
    private javax.swing.JMenu menuRelatoriosFornecedores;
    private javax.swing.JMenu menuRelatoriosFuncionarios;
    private javax.swing.JMenu menuRelatoriosHospedes;
    private javax.swing.JMenu menuRelatoriosReservas;
    private javax.swing.JMenuItem menuRelatoriosReservasFuturas;
    private javax.swing.JMenuItem menuRelatoriosReservasQuartosDisponiveis;
    private javax.swing.JMenuItem menuRelatoriosReservasQuartosOcupados;
    private javax.swing.JMenu menuRelatoriosVendas;
    private javax.swing.JMenuItem menuRelatoriosVendasProdutos;
    private javax.swing.JMenuItem menuRelatoriosVendasServicos;
    private javax.swing.JMenu menuReservas;
    private javax.swing.JMenu menuReservasCadastrar;
    private javax.swing.JMenu menuReservasConsultar;
    private javax.swing.JMenu menuReservasFinalizar;
    private javax.swing.JMenu menuSeguranca;
    private javax.swing.JMenu menuSegurancaFazerBackup;
    private javax.swing.JMenu menuSegurancaRestaurarBackup;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JMenu menuVendasProdutos;
    private javax.swing.JMenu menuVendasServicos;
    // End of variables declaration//GEN-END:variables
}
